char * addStrings(char * num1, char * num2)
{
    int s1,s2,i,j,k=0,z,y=0;
    char *p,temp;
    s1=strlen(num1);
    s2=strlen(num2);
    if(s1>=s2)
        i=s1;
    else
        i=s2;
    p=(char*)malloc(sizeof(char)*(i+2));
    s1--;s2--;
    if(s1<=s2)
        i=s1;
    else
        i=s2;
    while(i>=0)
    {
        z=y+num1[s1]+num2[s2]-96; 
        if(z>9)
        {
            p[k]='0'+z%10;
            y=z/10;
        }
        else
        {
            y=0;
            p[k]='0'+z;
        }
        k++;s1--;s2--;i--;
    }
    if(s2>=0)
    {
        while(s2>=0)
        {
            z=y+num2[s2]-48; 
            if(z>9)
            {
                p[k]='0'+z%10;
                y=z/10;
            }
            else
            {
                y=0;
                p[k]='0'+z;
            }
            k++;s2--;
        }
    }
    else if(s1>=0)
    {
        while(s1>=0)
        {
            z=y+num1[s1]-48; 
            if(z>9)
            {
                p[k]='0'+z%10;
                y=z/10;
            }
            else
            {
                y=0;
                p[k]='0'+z;
            }
            k++;s1--;
        }
    }
    if(y>0)
        p[k++]='1';
    p[k]='\0';
    j=k-1;
    for(i=0;i<k/2;i++)
    {
       temp=p[i];
        p[i]=p[j];
        p[j]=temp;
        j--;
    } 
    return p;
}
